volumes:
  imagera_local_postgres_data: {}
  imagera_local_postgres_data_backups: {}
  

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: imagera_local_django
    container_name: imagera_local_django
    depends_on:
      - postgres
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - .env
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: imagera_production_postgres
    container_name: imagera_local_postgres
    volumes:
      - imagera_local_postgres_data:/var/lib/postgresql/data
      - imagera_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
  
  actions:
    <<: *django
    image: imagera_local_rasa_actions
    container_name: imagera_local_rasa_actions
    depends_on:
      - postgres
      - django
      - rasa
    ports:
      - "5055:5055"
    command: /start-rasa-action

  rasa:
    <<: *django
    image: imagera_local_rasa
    container_name: imagera_local_rasa
    depends_on:
      - postgres
    ports:
      - "5005:5005"
    command: /start-rasa
